### ISSUE TITLE
Correios internacional

### ISSUE THREAD

**Issue by marcelowu** [dholidev/module-dholi-correios-frete-mirror#1]
Pretende fazer um plugins para frete internacional

**Comment by dholidev** [comment]
Oi Marcelo,

não está no roadmap os Correios Internacional.

Ano passado nós fizemos um estudo de preço internacional com os Correios, os valores estavam muito altos e o cliente desistiu.

Por ora, temos outros módulos para migrar do M1 para o M2 e alguns temas. Em meados de JUL/2020, devemos ter muita coisa bacana.

Pode deixar sua sugestão ela será avaliada.

Abraço.

**Comment by marcelowu** [comment]
ok, muito obrigado

**Comment by marcelowu** [comment]
Queria um calculo exatamente desse do correios no magento2
https://apps2.correios.com.br/efi/app/simulaPrecoPrazoInternacional/index.php
![Capturar11](https://user-images.githubusercontent.com/30912144/72667823-a622db00-39fe-11ea-9392-4eee8c67116d.PNG)
![Capturar12](https://user-images.githubusercontent.com/30912144/72667828-ab802580-39fe-11ea-9bdd-9c6eb2448ee3.PNG)
tem um exemplo do https://github.com/claudiosanches/woocommerce-correios/tree/master/includes/shipping

**Comment by marcelowu** [comment]
Imprimir etiquetas e PLP
https://github.com/stavarengo/php-sigep

**Comment by marcelowu** [comment]
https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json#!/Internacional/consultaPreco

**Comment by marcelowu** [comment]
tudo bem, achei o modulo correios internacional do woocommerce, vc faz para bagisto?

**Comment by dholidev** [comment]
Marcelo, bom dia.

Trabalhamos apenas com Magento.

Abraço.
